### ISSUE TITLE
Integrate metadata profile 1.3 (EML 2.2.0)

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/gbif-metadata-profile#24]
Integrate new profile https://github.com/gbif/eml-profile/issues/5

**Comment by mike-podolskiy90** [comment]
@MattBlissett I'm wondering about the new field `relatedProject`. I think we don't need to have all the parent project fields there. `title` and `abstract` (description) would be enough?

**Comment by MattBlissett** [comment]
Yes, I think so.
